#!/usr/bin/env node
"use strict";
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
class FixedDate extends Date { constructor(...args) { super(...(args.length ? args : ['2026-10-05T07:00:00Z'])); } }
const store = new Map();
const ctx = { Date: FixedDate, Intl, console, URL, location: {href:'https://example.org/'}, state:{data:{communityEvents:{events:[]}},view:'tab',tab:'today'}, localStorage: {getItem(key){return store.get(key) || null},setItem(key,value){store.set(key,value)}}, window:{}, document: {addEventListener(){},querySelector(){return null}}, render(){},requestAnimationFrame(){} };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(root,'event-schedule.js'),'utf8'),ctx);
const S = ctx.EventSchedule;
assert.equal(S.today(new Date('2026-10-04T15:00:00Z')),'2026-10-05');
assert.equal(S.day('2026-02-30'),null);
const single={startDate:'2026-10-25',endDate:'2026-10-25'};
const range={startDate:'2026-10-05',endDate:'2026-11-01'};
const split={startDate:'2026-10-05',endDate:'2026-10-25',occurrences:['2026-10-05','2026-10-25']};
assert.equal(S.happensOn(single,'2026-10-05'),false);
assert.equal(S.happensOn(single,'2026-10-25'),true);
assert.equal(S.happensOn(range,'2026-10-10'),true);
assert.equal(S.status(range,'2026-10-10'),'今日開催');
assert.equal(S.nextDate(range,'2026-10-10'),'2026-10-10');
assert.equal(S.happensOn(split,'2026-10-10'),false);
assert.equal(S.nextDate(split,'2026-10-10'),'2026-10-25');
assert.equal(S.nextDate(split,'2026-10-26'),'');
assert.equal(S.status(split,'2026-10-26'),'終了');
assert.equal(S.status({...range,status:'cancelled'},'2026-10-10'),'中止');
let source=fs.readFileSync(path.join(root,'civic-actions.js'),'utf8');
assert.ok(source.includes('querySelector("#ca-dialog-root button[data-ca-close]")?.focus()'));
source=source.replace(/  caEnsureDialog\(\);\n  caLoadRoutes\(\);\n  render\(\);\n\}\)\(\);\s*$/, '  globalThis.testReminder = caReminderFor; globalThis.testSave=caSaveEvent; globalThis.testRemove=caRemoveSavedEvent; globalThis.testSync=caSyncSavedEvents; globalThis.testIsSaved=caIsSaved; globalThis.testRefresh=caRefreshSaveActions;\n})();');
vm.runInContext(source,ctx);
assert.equal(ctx.testReminder(range).label,'今日開催');
assert.equal(ctx.testReminder({...single,applicationDeadline:'2026-10-04'}).label,'受付終了・10月25日開催');
assert.equal(ctx.testReminder({...single,applicationDeadline:'2026-10-05'}).label,'申込期限は今日');
assert.equal(ctx.testReminder({...single,applicationDeadline:'2026-10-06'}).label,'申込締切まであと1日');
assert.equal(ctx.testReminder({...range,status:'cancelled'}).label,'中止');
assert.equal(ctx.testReminder({...single,applicationDeadline:'2026-09-36'}).label,'日程を確認');
assert.equal(ctx.testReminder({startDate:'2026-02-30'}).label,'日程を確認');
assert.doesNotMatch(ctx.testReminder({...single,applicationDeadline:'2026-10-04'}).label,/あと-/);
assert.equal(S.status({...single,applicationDeadline:'2026-10-04'},'2026-10-05'),'開催予定・受付終了');
// Fixed fixture from the verified 2026-10-25 event; live feeds expire normally.
const closedReal={id:'closed-registration-fixture',title:'おぱんちゅうさぎ「はい!ち~ぢゅ!」',startDate:'2026-10-25',endDate:'2026-10-25',status:'scheduled',statusLabel:'受付終了',applicationStatus:'closed',when:'10月25日 11:00／13:00／15:00'};
assert.match(S.status(closedReal,'2026-10-05'),/受付終了/);
assert.match(ctx.testReminder(closedReal).label,/受付終了/);
assert.match(S.status({...single,applicationStatus:'unconfirmed'},'2026-10-05'),/受付状況を掲載元で確認/);
const current = {id:'test-event',title:'test',sourceUrl:'https://example.org/test',...range};
ctx.state.data.communityEvents.events = [current];
ctx.testSave({...current,startDate:'2026-09-01',endDate:'2026-09-01'});
ctx.testSave({...current,startDate:'2026-09-01',endDate:'2026-09-01'});
assert.equal(JSON.parse(store.get('mytown-saved-events-v1')).length,1,'repeated saves do not duplicate');
const synced = ctx.testSync();
assert.equal(synced[0].startDate,'2026-10-05','reminder receives latest corrected date');
assert.ok(synced[0].pendingChanges.length);
assert.equal(ctx.testReminder(synced[0]).label,'今日開催');
const attrs=new Map([['data-ca-open-saved','']]);
let savedClass=true;
const button={dataset:{caSaveStateId:'test-event'},classList:{toggle(_name,value){savedClass=value}},setAttribute(key,value){attrs.set(key,value)},removeAttribute(key){attrs.delete(key)}};
ctx.document.querySelectorAll=()=>[button];
ctx.testRemove('test-event');
ctx.testRefresh();
assert.equal(ctx.testIsSaved(current),false);
assert.equal(button.textContent,'🔖 保存する');
assert.equal(savedClass,false);
assert.equal(attrs.has('data-ca-open-saved'),false);
assert.equal(attrs.get('data-ca-save-event-id'),'test-event');
ctx.testRemove('test-event');
assert.equal(JSON.parse(store.get('mytown-saved-events-v1')).length,0,'repeated removal is safe');
console.log('Shared event schedule, deadline and save-state checks passed');
